### ISSUE TITLE
site shows eVDC related info

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_tfcloud_zola#2]
![image](https://github.com/threefoldfoundation/www_tfcloud_zola/assets/64129/1f08ab07-2beb-496b-b9f4-8331360bc62e)

![image](https://github.com/threefoldfoundation/www_tfcloud_zola/assets/64129/78b642fa-cd07-49be-96c4-cb2cca7ea839)

the eVDC project was a grid2 project. it's already dead.

**Comment by sasha-astiadi** [comment]
will bring this down and redir people to https://www.threefold.io/

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldtech/tf_operations/issues/1856

**Comment by sasha-astiadi** [comment]
deactivated
